name: xweights-tests
channels:
    - conda-forge
    - nodefaults
dependencies:
    - dask
    - geopandas
    - intake-esm
    - xarray
    - py-cordex
    - cartopy
    - xesmf
    - numpy
    - setuptools
    - pooch
    - netCDF4
    # for testing
    - pytest
    - pytest-cov
    - pytest-env
    - pip

    - pip:
      - pyhomogenize
