name: xweights-tests

channels:
    - conda-forge
    - nodefaults

dependencies:
    - dask
    - geopandas
    - xarray
    - py-cordex
    - cartopy
    - xesmf
    - numpy
    - setuptools
    - pooch
    - pip
    # for testing
    - pytest
    - pytest-cov
    - pytest-env

    - pip:
      - pyhomogenize
